requirejs([
  'app/views/banner',
  'app/views/navbar',
  'app/views/buttons',
  'app/views/typography',
  'app/views/tables',
  'app/views/forms',
  'app/views/navs',
  'app/views/indicators',
  'app/views/progress-bars',
  'app/views/containers',
  'app/views/dialogs',
  'app/views/footer'
]);
